# Ansible inventory created from ['/workspaces/netlab/challenge1/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: python:3.9-alpine
clab:
  binds:
  - clab_files/h4/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-challenge1-h4
interfaces:
- bridge: challenge1_7
  gateway:
    ipv4: 172.16.3.4/24
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.3.8/24
  linkindex: 7
  mtu: 1500
  name: h4 -> isp2
  neighbors:
  - ifname: eth2
    ipv4: 172.16.3.4/24
    node: isp2
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.108
  mac: 08:4f:a9:00:00:08
mtu: 1500
role: host
