# Ansible inventory created from ['/home/sama/netlab/challenge2/topology.yml', 'package:topology-defaults.yml']
#

all: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
frr:
  hosts:
    r1:
      ansible_host: clab-challenge2-r1
      id: 1
    r2:
      ansible_host: clab-challenge2-r2
      id: 2
    r3:
      ansible_host: clab-challenge2-r3
      id: 3
    r4:
      ansible_host: clab-challenge2-r4
      id: 4
linux:
  hosts:
    h3:
      ansible_host: clab-challenge2-h3
      id: 7
    h4:
      ansible_host: clab-challenge2-h4
      id: 8
    server1:
      ansible_host: clab-challenge2-server1
      id: 5
    server2:
      ansible_host: clab-challenge2-server2
      id: 6
modules:
  hosts:
    r1: {}
    r2: {}
    r3: {}
    r4: {}
